#!/bin/bash
#change this to the name of your service: ex: "elephantsql"
export SERVICE_NAME=user-provided
if [ $PORT ]; 
   then
       PYTHON='.conda/bin/python'
       echo 'Using python:'$PYTHON
   else 
       PYTHON=`which python`
       echo 'Using python:'$PYTHON
fi
#Install the app
$PYTHON setup.py build
$PYTHON setup.py install
#Start the webserver
$PYTHON -m dspcfapp
